### ISSUE TITLE
Broken build caused by old component package being removed from npm

### ISSUE THREAD

**Issue by SteveALee** [littlesticks/odyssey-theme#19]
I'm trying to build but do not yet want to upgrade to the latest version. Don;t have the time as this is a breaking change.

However npm install now fails on clean machine as you have deleted the old package from npm.

Can you please reinstate the old package or provide me with a version I can use locally?

Thanks

**Comment by SteveALee** [comment]
Actually as Netlify CD is a clean machine that is now broken for us :(

**Comment by SteveALee** [comment]
```
4:16:28 PM: npm ERR! 404  '@odyssey-theme/components@https://registry.npmjs.org/@odyssey-theme/components/-/components-0.1.67.tgz' is not in this registry.
```

**Comment by SteveALee** [comment]
Moral of the story - never delete npm packages if they can have a user :(

**Comment by SteveALee** [comment]
I guess I'll have to merge your 2.0.0 changes after all.

**Comment by SteveALee** [comment]
So in the end I installed the 1.0.0 components in th src and edited all the includes (including one in the components themselves)

**Comment by jaydanurwin** [comment]
Sorry for the rough upgrade @SteveALee I wasn't wanting to do that but it would have forced me to keep an npm organization for what was only ever going to be one package. `@odyssey-theme` was the org it was under. I learned the hard way that I made the wrong decision in naming and setup for the theme components.

The components shipped as an npm package isn't really a model I'm going to use going forward either. It was a requirement for Astro's hackathon which is why I did it that way. People have given a lot of feedback about it being confusing for newcomers and it just isn't a pattern people are used to.

All good lessons and again I'm sorry for the bumpy process. I was hoping for the most part people would be able to swap `@odyssey-theme/components` for the new `@littlesticks/odyssey-theme-components` and I think you largely can because it's the same code minus a couple tweaks.

Let me know if there's anything I can do help migrate your existing projects to the new package.

**Comment by jaydanurwin** [comment]
@SteveALee Can you elaborate on the "page not found" issue you were seeing with astro-icon? That might be a separate issue I need to look into but I can't seem to reproduce it. Thanks!

**Comment by SteveALee** [comment]
Thanks for confirming it should be an easy switch to the new package.  for now the old ones are copied across to my project.

I can't recall the exact reason for the 404. I think it was just trying to rebuild after cleaning the npm cache so the old package was no longer available on my dev machine.

**Comment by irfanirshad** [comment]
> @SteveALee Can you elaborate on the "page not found" issue you were seeing with astro-icon? That might be a separate issue I need to look into but I can't seem to reproduce it. Thanks!

I think I might have reproduced this very same issue. This morning I duplicated an already working odyssey-theme repo and tried running npm install && npm start and it just broke everthing and started throwing the "404: Not found
Path: /" astro icon page  for me.

**Comment by irfanirshad** [comment]
I then npm globally installed astro and typescript because .....(insert some stupid reason that's probably not the real problem here) just to make sure.  No workie. 

I ran the astro build and astro check and it throws up some error I'm not sure what it means. It's something to do with Vite. 
Attaching the error message below:
`[vite]: Rollup failed to resolve import "astro/jsx/server.js" from "@astrojs-pages-virtual-entry".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
 error   [vite]: Rollup failed to resolve import "astro/jsx/server.js" from "@astrojs-pages-virtual-entry".
  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  File:
    /usr/local/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44636:19
  Code:
    44635 |         if (!id || !/\?commonjs-external$/.test(id)) {
    > 44636 |             throw new Error(`[vite]: Rollup failed to resolve import "${exporter}" from "${id}".\n` +
            |                   ^
      44637 |                 `This is most likely unintended because it can break your application at runtime.\n` +
      44638 |                 `If you do want to externalize this module explicitly add it to\n` +
      44639 |                 `\`build.rollupOptions.external\``);
  Stacktrace:
Error: [vite]: Rollup failed to resolve import "astro/jsx/server.js" from "@astrojs-pages-virtual-entry".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///usr/local/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44636:19)
    at onwarn (file:///usr/local/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44407:13)
    at Object.onwarn (file:///usr/local/lib/node_modules/astro/node_modules/rollup/dist/es/shared/rollup.js:24518:13)
    at ModuleLoader.handleInvalidResolvedId (file:///usr/local/lib/node_modules/astro/node_modules/rollup/dist/es/shared/rollup.js:23199:26)
    at file:///usr/local/lib/node_modules/astro/node_modules/rollup/dist/es/shared/rollup.js:23159:26`
