### ISSUE TITLE
> @SteveALee Can you elaborate on the "page not found" issue you were seeing with astro-icon? That might be a separate issue I need to look into but I can't seem to reproduce it. Thanks!

### ISSUE THREAD

**Issue by irfanirshad** [littlesticks/odyssey-theme#23]
> @SteveALee Can you elaborate on the "page not found" issue you were seeing with astro-icon? That might be a separate issue I need to look into but I can't seem to reproduce it. Thanks!

I think I might have reproduced this very same issue. This morning I duplicated an already working odyssey-theme repo and tried running npm install && npm start and it just broke everthing and started throwing the "404: Not found
Path: /" astro icon page  for me.

_Originally posted by @irfanirshad in https://github.com/littlesticks/odyssey-theme/issues/19#issuecomment-1405214319_

**Comment by irfanirshad** [comment]
I then npm globally installed astro and typescript because .....(insert some stupid reason that's probably not the real problem here) just to make sure. No workie.

I ran the astro build and astro check and it throws up some error I'm not sure what it means. It's something to do with Vite.
Attaching the error message below:
[vite]: Rollup failed to resolve import "astro/jsx/server.js" from "@astrojs-pages-virtual-entry". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to build.rollupOptions.externalerror   [vite]: Rollup failed to resolve import "astro/jsx/server.js" from "@astrojs-pages-virtual-entry". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it tobuild.rollupOptions.external File: /usr/local/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44636:19 Code: 44635 |         if (!id || !/\?commonjs-external$/.test(id)) { > 44636 |             throw new Error([vite]: Rollup failed to resolve import "${exporter}" from "${id}".\n+ |                   ^ 44637 |                This is most likely unintended because it can break your application at runtime.\n+ 44638 |                If you do want to externalize this module explicitly add it to\n+ 44639 |                `build.rollupOptions.external`); Stacktrace: Error: [vite]: Rollup failed to resolve import "astro/jsx/server.js" from "@astrojs-pages-virtual-entry". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to build.rollupOptions.external at onRollupWarning (file:///usr/local/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44636:19) at onwarn (file:///usr/local/lib/node_modules/astro/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44407:13) at Object.onwarn (file:///usr/local/lib/node_modules/astro/node_modules/rollup/dist/es/shared/rollup.js:24518:13) at ModuleLoader.handleInvalidResolvedId (file:///usr/local/lib/node_modules/astro/node_modules/rollup/dist/es/shared/rollup.js:23199:26) at file:///usr/local/lib/node_modules/astro/node_modules/rollup/dist/es/shared/rollup.js:23159:26
